title: London Crypto Day 2020
description: Fall 2020 at Google London (Soho)
theme: jekyll-theme-cayman
logo: img/london.jpg
register: https://docs.google.com/forms/d/e/1FAIpQLSeLJf96tNmdgRXdm3h4VXmgphX_iPFjyv1aVgRpuLuYMSRt6A/viewform
